variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: F1
  - name: F2

edges:
  - effect: O1
    equation: "5*F2 + 0.56*F1"
  - effect: A
    equation: "-70*F1 + 10*F2 + 70*O2"
  - effect: Y
    equation: "0.4*A + 0.68*O1 + 0.14*O2"