variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: F1
  - name: F2

edges:
  - effect: O1
    equation: "1*F2 + 1*F1"
  - effect: A
    equation: "-1*F1 + 0.1*F2 + 10*O2"
  - effect: Y
    equation: "3*A + 5*O1 + 0.7*O2"