variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: F1
  - name: F2

edges:
  - effect: O1
    equation: "5*F2 + 0.5*F1"
  - effect: A
    equation: "-7*F1 + 1*F2 + 7*O2"
  - effect: Y
    equation: "3*A + 1*O1 + 0.4*O2"