variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: F1
  - name: F2

edges:
  - effect: O1
    equation: "0.9*F2 + 0.1*F1"
  - effect: A
    equation: "-0.7*F1 + 0.1*F2 + 0.7*O2"
  - effect: Y
    equation: "0.1*A + 0.5*O1 + 0.1*O2"