variables:
  - name: A
  - name: Y
  - name: J1
  - name: O1
  - name: O2
  - name: O3
  - name: O4
  - name: O5
  - name: O6
  - name: O7
  - name: O8
  - name: O9
  - name: O10
  - name: O11
  - name: O12
  - name: O13
  - name: O14
  - name: O15
  - name: O16
  - name: O17
  - name: O18
  - name: O19
  - name: O20
  - name: O21
  - name: O22
  - name: O23
  - name: O24
  - name: O25
  - name: O26
  - name: O27
  - name: O28
  - name: O29
  - name: O30
  - name: O31
  - name: O32
  - name: O33
  - name: O34
  - name: O35
  - name: O36
  - name: O37
  - name: O38
  - name: O39
  - name: O40
  - name: O41
  - name: O42
  - name: O43
  - name: O44
  - name: O45
  - name: O46
  - name: O47
  - name: O48
  - name: O49
  - name: O50

edges:
  - effect: O1
    equation: "0.9*J1"
  - effect: O2
    equation: "0.9*J1"
  - effect: O3
    equation: "0.9*J1"
  - effect: O4
    equation: "0.9*J1"
  - effect: O5
    equation: "0.9*J1"
  - effect: O6
    equation: "0.9*J1"
  - effect: O7
    equation: "0.9*J1"
  - effect: O8
    equation: "0.9*J1"
  - effect: O9
    equation: "0.9*J1"
  - effect: O10
    equation: "0.9*J1"
  - effect: O11
    equation: "0.9*J1"
  - effect: O12
    equation: "0.9*J1"
  - effect: O13
    equation: "0.9*J1"
  - effect: O14
    equation: "0.9*J1"
  - effect: O15
    equation: "0.9*J1"
  - effect: O16
    equation: "0.9*J1"
  - effect: O17
    equation: "0.9*J1"
  - effect: O18
    equation: "0.9*J1"
  - effect: O19
    equation: "0.9*J1"
  - effect: O20
    equation: "0.9*J1"
  - effect: O21
    equation: "0.9*J1"
  - effect: O22
    equation: "0.9*J1"
  - effect: O23
    equation: "0.9*J1"
  - effect: O24
    equation: "0.9*J1"
  - effect: O25
    equation: "0.9*J1"
  - effect: O26
    equation: "0.9*J1"
  - effect: O27
    equation: "0.9*J1"
  - effect: O28
    equation: "0.9*J1"
  - effect: O29
    equation: "0.9*J1"
  - effect: O30
    equation: "0.9*J1"
  - effect: O31
    equation: "0.9*J1"
  - effect: O32
    equation: "0.9*J1"
  - effect: O33
    equation: "0.9*J1"
  - effect: O34
    equation: "0.9*J1"
  - effect: O35
    equation: "0.9*J1"
  - effect: O36
    equation: "0.9*J1"
  - effect: O37
    equation: "0.9*J1"
  - effect: O38
    equation: "0.9*J1"
  - effect: O39
    equation: "0.9*J1"
  - effect: O40
    equation: "0.9*J1"
  - effect: O41
    equation: "0.9*J1"
  - effect: O42
    equation: "0.9*J1"
  - effect: O43
    equation: "0.9*J1"
  - effect: O44
    equation: "0.9*J1"
  - effect: O45
    equation: "0.9*J1"
  - effect: O46
    equation: "0.9*J1"
  - effect: O47
    equation: "0.9*J1"
  - effect: O48
    equation: "0.9*J1"
  - effect: O49
    equation: "0.9*J1"
  - effect: O50
    equation: "0.9*J1"
  - effect: Y
    equation: "0.2*A + 0.1*(O1 + O2 + O3 + O4 + O5 + O6 + O7 + O8 + O9 + O10 + O11 + O12 + O13 + O14 + O15 + O16 + O17 + O18 + O19 + O20 + O21 + O22 + O23 + O24 + O25 + O26 + O27 + O28 + O29 + O30 + O31 + O32 + O33 + O34 + O35 + O36 + O37 + O38 + O39 + O40 + O41 + O42 + O43 + O44 + O45 + O46 + O47 + O48 + O49 + O50)"