id: m1

variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: W1
  - name: W2

edges:
  - effect: O1
    equation: "2*W2 + 2*W1"
  - effect: A
    equation: "-1*W1 + 0.1*W2 + 40*O2"
  - effect: Y
    equation: "3*A + 5*O1 + 0.5*O2"