variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: I
  - name: M

edges:
  - effect: M
    equation: "0.7*O1 + 0.2*I"
  - effect: A
    equation: "0.3*I + 0.6*O2"
  - effect: Y
    equation: "0.2*A + 0.5*O1 + 0.1*O2"


