variables:
  - name: A
  - name: Y
  - name: O1
  - name: O2
  - name: I1
  - name: M1

edges:
  - effect: M1
    equation: "0.9*O1 + 0.2*I1"
  - effect: A
    equation: "0.3*I1 + 0.6*O2"
  - effect: Y
    equation: "0.2*A + 0.5*O1 + 0.1*O2"


